# Site settings
title: a vendre / for sale
destination: #../public/avendre/
description: My sale of furniture and other things.
baseurl: "/jekyll-garagesale" # '/u/4625163/avendre' # leave empty '' if hosted directly at domain level, otherwise put sub-domain without an ending dash.
url: "https://fdschneider.github.io" #'https://dl.dropboxusercontent.com' # the base hostname & protocol for your site # "https://dl.dropboxusercontent.com" for Dropbox, "http://username.github.com" for Github

name : Florian Schneider
email : flo_schneider@web.de
github_username: fdschneider
twitter_username: f-d-schneider
website : http://fdschneider.github.io/

permalink: /:categories/:title.html
include: [_posts]

# Build settings
markdown: kramdown
kramdown:
  input: GFM

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: article
